services:
  - type: web
    name: backendchat
    env: node
    buildCommand: npm install && npm run build
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
